import { Inter } from "next/font/google";
import "./global.css";
import Link from "next/link"; //used for client side navigation between pages
import headerStyles from "./Header/header.module.css";

const inter = Inter({ subsets: ["latin"] }); // font configuration

export const metadata = {
  title: "Create Next App",
  description: "Generated by create app",
};
// provides metadata for the page

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={headerStyles.header}>
          <h1>The Books Hub</h1>
          <nav id="nav">
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/contact">Contact</Link>
          </nav>
        </header>
        {children}
        <footer class="footer">
          <div class="footer-bottom">
            <p>&copy; 2024 The Books Club - All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
// RootLayout component provides consistent layout across all pages, for consistent styling and structure throughout the app
